# -*- coding: utf-8 -*-
"""parser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ljyBIOZFXAEE7rq2PY-OmDDPdHlHgV-y
"""

import json
from google.colab import files

uploaded = files.upload()

import re
import pandas as pd
import json

def parser(names):
  dict = {}
  for name in names:
    with open(name + '.txt') as f:
        lines = f.readlines()

    state_size, func_name = 0, ''
    d = {}

    for line in lines:
      if 'State' in line:
        state_size = re.findall('\d+', line)[0]

      if not func_name and 'Passed' in line:
        func_name = re.findall('^[A-Za-z]+\d*', line)[0]

      if func_name and 'Passed' not in line and func_name in line:
        operation = re.findall('[A-Za-z]+', line)[1]
        res = re.findall('\d+[.]\d+\w*', line)

        if len(res) != 2: 
          continue

        res[0] += ' per/op'
        res[1] += ' per/sec'
        d[operation] = res

    d['State_size'] = state_size
    dict[func_name] = d

  return dict

#parser returns dictionary so we can change the result 
#into whatever form we want 
d = parser(['output', 'sample'])
result = json.dumps(d)

pd.DataFrame.from_dict(d)